#ifndef __LSYSTEM_HPP__
#define __LSYSTEM_HPP__ 1

#include <string>
#include <unordered_map>
#include <vector>
#include <random>

/**
 * @class LSystem
 * @brief Implementation of an L-system for tree structure generation.
 *
 * This class provides functionality to define and process L-systems,
 * which are formal systems used to model plant growth.
 * It allows setting an initial axiom and production rules, and generating strings
 * through iterative application of these rules.
 */
class LSystem {
public:

    /**
     * @brief Default constructor for the LSystem class.
     */
    LSystem();

    /**
     * @brief Sets the initial axiom of the L-system.
     * @param axiom String representing the initial axiom.
     */
    void setAxiom(const std::string& axiom);

    /**
    * @brief Adds a production rule to the L-system.
    * @param predecessor Character that will be replaced.
    * @param successor String that will replace the predecessor.
    */
    void addRule(char predecessor, const std::string& successor);

    /**
     * @brief Generates the L-system string by applying rules a specific number of times.
     * @param iterations Number of iterations to perform.
     */
    void generate(int iterations);

    /**
    * @brief Resets the L-system to its initial state (axiom).
    */
    void reset();


    /**
     * @brief Gets the current string generated by the L-system.
     * @return String representing the current state of the L-system.
     */
    std::string getCurrent() const;

    /**
    * @brief Performs a single iteration by applying the current rules.
    */
    void iterate();

    /**
     * @brief Generates guided rules based on a specific action.
     * @param action Identifier of the action that determines the rules to generate.
     */
    void generateGuidedRules(int action);

    /**
    * @brief Generates random production rules for the L-system.
    */
    void generateRandomRules(); 

    /**
   * @brief Advances to the next step in guided mode.
   * @param choice Selected option for the next step.
   */
    void nextGuidedStep(int choice); 

    /**
    * @brief Gets the current step in guided mode.
    * @return Integer representing the current step.
    */
    int getGuidedStep() const { return guidedStep; }

    /**
    * @brief Resets the guided mode.
    */
    void resetGuided();
private:
    std::string originalAxiom;  ///< Original axiom of the L-system
    std::string current;        ///< Current string generated by the L-system
    std::unordered_map<char, std::string> rules;  ///< Production rules of the L-system
    int guidedStep = 0;         ///< Current step in guided mode
};

#endif
