#ifndef __TREE_RENDERED_HPP__
#define __TREE_RENDERED_HPP__ 1


#include <SFML/Graphics.hpp>
#include <stack>
#include <cmath>
#include "LSystem.hpp"

/**
 * @class TreeRenderer
 * @brief Class for rendering trees generated by L-systems in 2D using SFML.
 *
 * This class interprets strings generated by an L-system and renders them
 * as tree structures in 2D using the SFML library. It converts
 * the characters in the string into graphic operations, such as drawing lines
 * and rotating the drawing direction.
 */
class TreeRenderer {
public:
    /**
    * @brief Constructor for the TreeRenderer class.
    * @param lSystem Reference to an LSystem object that provides the string to render.
    * @param window Reference to the SFML window where the tree will be drawn.
    * @param angle Rotation angle in degrees for branching (default 25.0f).
    * @param length Length of each tree segment (default 10.0f).
    */
    TreeRenderer(const LSystem& lSystem, sf::RenderWindow& window, float angle = 25.0f, float length = 10.0f);

    /**
    * @brief Draws the tree in the SFML window.
    *
    * Interprets the current string from the L-system and draws it as a tree
    * in the provided SFML window.
    */
    void draw();

private:
    const LSystem& lSystem;     ///< Reference to the L-system that provides the string to render
    sf::RenderWindow& window;   ///< Reference to the SFML window where the tree will be drawn

    const float ANGLE;          ///< Rotation angle for branching in degrees
    const float LENGTH;         ///< Length of each tree segment

    /**
     * @struct Point
     * @brief Structure to represent a point in 2D space.
     */
    struct Point {
        float x, y; ///< X and Y coordinates of the point
        /**
        * @brief Constructor for the Point structure.
        * @param x X coordinate (default 0).
        * @param y Y coordinate (default 0).
        */
        Point(float x = 0, float y = 0) : x(x), y(y) {}
    };

    /**
    * @brief Private method that implements the tree drawing algorithm.
    * @param lSystemString L-system string to interpret and draw.
    */
    void drawTree(const std::string& lSystemString);
};


#endif // !__TREE_RENDERED_HPP__
