#ifndef TREE_TO_OBJ_CONVERTER_HPP
#define TREE_TO_OBJ_CONVERTER_HPP

#include <vector>
#include <stack>
#include <string>
#include <fstream>
#include <cmath>
#include <iostream>
#include <random>
#include <ctime>
#ifndef M_PI
#   define M_PI 3.1415926535897932384626433832
#endif

/**
 * @struct Point3D
 * @brief Structure to represent a point in 3D space.
 */
struct Point3D {
    float x, y, z;///< X, Y, Z coordinates of the point
    
    /**
     * @brief Constructor for the Point3D structure.
     * @param _x X coordinate (default 0).
     * @param _y Y coordinate (default 0).
     * @param _z Z coordinate (default 0).
     */
    Point3D(float _x = 0, float _y = 0, float _z = 0) : x(_x), y(_y), z(_z) {}
};

/**
 * @struct Segment3D
 * @brief Structure to represent a 3D segment (branch or trunk of the tree).
 */
struct Segment3D {
    Point3D start;      ///< Starting point of the segment
    Point3D end;        ///< Ending point of the segment
    float thickness;    ///< Thickness of the segment

    /**
    * @brief Constructor for the Segment3D structure.
    * @param _start Starting point.
    * @param _end Ending point.
    * @param _thickness Thickness of the segment.
    */
    Segment3D(Point3D _start, Point3D _end, float _thickness)
        : start(_start), end(_end), thickness(_thickness) {}
};

/**
 * @struct Face
 * @brief Structure to represent a face in a 3D model (OBJ format).
 */
struct Face {
    std::vector<int> vertexIndices;///< Indices of the vertices that make up the face
    /**
    * @brief Default constructor.
    */
    Face() {}

    /**
     * @brief Constructor that initializes with a list of indices.
     * @param indices Initializer list with vertex indices.
     */
    Face(std::initializer_list<int> indices) : vertexIndices(indices) {}
};

/**
 * @enum LeafType
 * @brief Types of leaves that can be generated in the 3D model.
 */
enum class LeafType {
    SIMPLE,     ///< Simple leaf (diamond shape)
    NEEDLE,     ///< Needle-like (typical of conifers)
    BROAD,      ///< Broad leaf (typical of deciduous trees)
    PALM,        ///< Palm tree leaf
    COMPOUND
};

/**
 * @class TreeToObjConverter
 * @brief Class for converting trees generated by L-systems to 3D models in OBJ format.
 *
 * This class interprets strings generated by an L-system and converts them
 * into complete 3D models, with trunks, branches, and leaves, saving them in OBJ format.
 * It allows configuring various aspects of the model, such as cylinder resolution,
 * leaf size, and leaf type.
 */

class TreeToObjConverter {
private:
    std::vector<Segment3D> segments;  ///< Segments (branches/trunks) of the tree
    std::vector<Point3D> leafPoints;   ///< Points where leaves will be placed
    std::string outputFilename;        ///< Name of the output OBJ file
    int cylinderResolution;            ///< Resolution of the cylinders (number of segments)
    float leafSize;                    ///< Size of the leaves
    bool generateLeaves;               ///< Indicates whether leaves should be generated
    float randomnessFactor;            ///< Randomness factor for generation
    float branchMultiplier;            ///< Multiplier for branch radius
    LeafType leafType;                 ///< Type of leaf to generate
    std::mt19937 rng;                  ///< Random number generator


public:

    /**
    * @brief Constructor for the TreeToObjConverter class.
    * @param filename Name of the output OBJ file (default "tree3d.obj").
    * @param resolution Resolution of the cylinders (default 8).
    */
    TreeToObjConverter(const std::string& filename = "tree3d.obj", int resolution = 8)
        : outputFilename(filename), cylinderResolution(resolution), leafSize(0.5f), generateLeaves(true), branchMultiplier(1.0f) {}

    /**
     * @brief Sets the size of the leaves.
     * @param size Size of the leaves.
     */
    void setLeafSize(float size) { leafSize = size; }

    /**
    * @brief Enables or disables leaf generation.
    * @param generate True to generate leaves, false to not generate them.
    */
    void setGenerateLeaves(bool generate) { generateLeaves = generate; }

    /**
    * @brief Sets the resolution of the cylinders (branches/trunks).
    * @param resolution Number of segments for the circumference of the cylinder.
    */
    void setCylinderResolution(int resolution) { cylinderResolution = resolution; }

    /**
     * @brief Sets the randomness factor for generation.
     * @param factor Randomness factor (higher value = more random).
     */
    void setRandomnessFactor(float factor) { randomnessFactor = factor; }

    /**
    * @brief Sets the multiplier for branch radius.
    * @param multiplier Multiplier (higher value = thicker branches).
    */
    void setBranchRadiusMultiplier(float multiplier) { branchMultiplier = multiplier; }

    /**
    * @brief Sets the type of leaves to generate.
    * @param type Leaf type according to the LeafType enumeration.
    */
    void setLeafType(LeafType type) { leafType = type; }

    /**
     * @brief Gets the currently configured leaf type.
     * @return Current leaf type.
     */
    LeafType getLeafType() const { return leafType; }

    /**
     * @brief Gets the names of the different available leaf types.
     * @return Vector of strings with the names of the leaf types.
     */
    static std::vector<std::string> getLeafTypeNames() {
        return {
            "Simple",
            "Acicular",
            "Frondosas",
            "Palmera",
            "Compuesta"
        };
    };


    /**
     * @brief Converts an L-system string to a 3D model.
     * @param lSystemString String generated by the L-system.
     * @param initialAngle Initial angle for interpretation.
     * @param initialLength Initial length of the segments.
     * @param initialWidth Initial width of the segments.
     * @return True if the conversion was successful, false otherwise.
     */
    bool convertLSystemToObj(const std::string& lSystemString, float initialAngle, float initialLength, float initialWidth);

    /**
    * @brief Generates the OBJ file with a progress bar.
    * @param progress Reference to an atomic value that will be updated with progress (0.0-1.0).
    * @return True if generation was successful, false otherwise.
    */
    bool generateOBJ(std::atomic<float>& progress);

    /**
    * @brief Generates the OBJ file without a progress bar.
    * @return True if generation was successful, false otherwise.
    */
    bool generateOBJ();

private:
    /**
    * @brief Adds a cylinder to the 3D model.
    * @param segment Segment that defines the cylinder to add.
    * @param vertices Vector of model vertices to which new vertices will be added.
    * @param faces Vector of model faces to which new faces will be added.
    */
    void addCylinder(const Segment3D& segment, std::vector<Point3D>& vertices, std::vector<Face>& faces);

    /**
    * @brief Adds a leaf to the 3D model.
    * @param position Position where the leaf will be added.
    * @param size Size of the leaf.
    * @param vertices Vector of model vertices to which new vertices will be added.
    * @param faces Vector of model faces to which new faces will be added.
    */
    void addLeaf(const Point3D& position, float size, std::vector<Point3D>& vertices, std::vector<Face>& faces);

    /**
    * @brief Calculates perpendicular vectors to a given direction.
    * @param direction Direction vector.
    * @param perpendicular1 [out] First calculated perpendicular vector.
    * @param perpendicular2 [out] Second calculated perpendicular vector.
    */
    void calculatePerpendicularVectors(const Point3D& direction, Point3D& perpendicular1, Point3D& perpendicular2);

    /**
     * @brief Normalizes a 3D vector (length = 1).
     * @param vector Vector to normalize.
     * @return Normalized vector.
     */
    Point3D normalizeVector(const Point3D& vector);

    /**
    * @brief Adds a simple leaf (diamond) to the model.
    * @param position Position where the leaf will be added.
    * @param size Size of the leaf.
    * @param vertices Vector of model vertices to which new vertices will be added.
    * @param faces Vector of model faces to which new faces will be added.
    */
    void addSimpleLeaf(const Point3D& position, float size, std::vector<Point3D>& vertices, std::vector<Face>& faces);

    /**
    * @brief Adds a needle leaf (conifer) to the model.
    * @param position Position where the leaf will be added.
    * @param size Size of the leaf.
    * @param vertices Vector of model vertices to which new vertices will be added.
    * @param faces Vector of model faces to which new faces will be added.
    */
    void addNeedleLeaf(const Point3D& position, float size, std::vector<Point3D>& vertices, std::vector<Face>& faces);
    
    /**
     * @brief Adds a broad leaf (deciduous) to the model.
     * @param position Position where the leaf will be added.
     * @param size Size of the leaf.
     * @param vertices Vector of model vertices to which new vertices will be added.
     * @param faces Vector of model faces to which new faces will be added.
     */
    void addBroadLeaf(const Point3D& position, float size, std::vector<Point3D>& vertices, std::vector<Face>& faces);
    
    /**
    * @brief Adds a palm leaf to the model.
    * @param position Position where the leaf will be added.
    * @param size Size of the leaf.
    * @param vertices Vector of model vertices to which new vertices will be added.
    * @param faces Vector of model faces to which new faces will be added.
    */
    void addPalmLeaf(const Point3D& position, float size, std::vector<Point3D>& vertices, std::vector<Face>& faces);
    /**
    * @brief Adds a compound leaf (like fern or ash) to the model.
    * @param position Position where the leaf will be added.
    * @param size Size of the leaf.
    * @param vertices Vector of model vertices to which new vertices will be added.
    * @param faces Vector of model faces to which new faces will be added.
    */
    void addCompoundLeaf(const Point3D& position, float size, std::vector<Point3D>& vertices, std::vector<Face>& faces);

    /**
     * @brief Calculates the orientation of a leaf.
     * @param position Leaf position.
     * @param right [out] Vector representing the right direction.
     * @param up [out] Vector representing the up direction.
     * @param forward [out] Vector representing the forward direction.
     */
    void calculateLeafOrientation(const Point3D& position, Point3D& right, Point3D& up, Point3D& forward);

    /**
    * @brief Generates a random floating-point number in a given range.
    * @param min Minimum value of the range.
    * @param max Maximum value of the range.
    * @return Random floating-point number in the range [min, max].
    */
    float randomFloat(float min, float max) {
        std::uniform_real_distribution<float> dist(min, max);
        return dist(rng);
    }
};

#endif // TREE_TO_OBJ_CONVERTER_HPP